[package]
name = "restart_router"
version = "0.1.0"
authors = ["cato b <cato.benjaminsen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curl = "0.4.34"
